[
  {
    id: 1,
    title: "Create Project Proposal",
    description: "Draft the initial project proposal and review feedback.",
    status: 1,
    dueDate: 1733846400000,
  },
  {
    id: 2,
    title: "Design Wireframes",
    description: "Prepare wireframes for the user interface design.",
    status: 2,
    dueDate: 1734172800000,
  },
  {
    id: 3,
    title: "Set Up Backend",
    description: "Initialize the backend environment with necessary tools.",
    status: 1,
    dueDate: 1734259200000,
  },
  {
    id: 4,
    title: "Develop API Endpoints",
    description: "Create endpoints for user authentication and data retrieval.",
    status: 2,
    dueDate: 1734528000000,
  },
  {
    id: 5,
    title: "Write Test Cases",
    description: "Draft unit and integration test cases for the API.",
    status: 1,
    dueDate: 1734720000000,
  },
  {
    id: 6,
    title: "Review Codebase",
    description: "Perform a code review to ensure quality standards.",
    status: 3,
    dueDate: 1733251200000,
  },
  {
    id: 7,
    title: "Update Documentation",
    description: "Update project documentation with the latest changes.",
    status: 2,
    dueDate: 1734806400000,
  },
  {
    id: 8,
    title: "Deploy Application",
    description: "Deploy the application to the staging environment.",
    status: 1,
    dueDate: 1735084800000,
  },
  {
    id: 9,
    title: "Fix UI Bugs",
    description: "Address user-reported bugs in the interface design.",
    status: 3,
    dueDate: 1733164800000,
  },
  {
    id: 10,
    title: "Organize Team Meeting",
    description: "Schedule a meeting to discuss project milestones.",
    status: 1,
    dueDate: 1733913600000,
  },
  {
    id: 11,
    title: "Conduct User Interviews",
    description: "Gather feedback by interviewing potential users.",
    status: 2,
    dueDate: 1734268800000,
  },
  {
    id: 12,
    title: "Integrate Payment Gateway",
    description: "Add and test payment processing functionality.",
    status: 1,
    dueDate: 1734902400000,
  },
  {
    id: 13,
    title: "Optimize Database Queries",
    description: "Enhance database query performance for scalability.",
    status: 2,
    dueDate: 1734998400000,
  },
  {
    id: 14,
    title: "Plan Marketing Strategy",
    description: "Develop a strategy for the product launch marketing.",
    status: 3,
    dueDate: 1733337600000,
  },
  {
    id: 15,
    title: "Prepare Demo Presentation",
    description: "Create slides and scripts for the product demo.",
    status: 1,
    dueDate: 1734000000000,
  },
  {
    id: 16,
    title: "Refactor Old Code",
    description: "Refactor legacy code to improve maintainability.",
    status: 2,
    dueDate: 1734864000000,
  },
  {
    id: 17,
    title: "Setup CI/CD Pipeline",
    description: "Implement continuous integration and deployment workflows.",
    status: 1,
    dueDate: 1735392000000,
  },
  {
    id: 18,
    title: "Conduct Usability Testing",
    description: "Perform usability tests to refine the user experience.",
    status: 2,
    dueDate: 1734432000000,
  },
  {
    id: 19,
    title: "Finalize Budget Report",
    description: "Prepare the final budget report for project approval.",
    status: 3,
    dueDate: 1733500800000,
  },
  {
    id: 20,
    title: "Launch Product",
    description: "Release the product to the production environment.",
    status: 1,
    dueDate: 1735680000000,
  },
];
